# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_hello <- function() {
    .Call(`_ZIMHMM_rcpp_hello`)
}

Viterbi <- function(LOGF, P, GAMMA) {
    .Call(`_ZIMHMM_Viterbi`, LOGF, P, GAMMA)
}

hmm_logF <- function(logf1, logf2, pi, gamma) {
    .Call(`_ZIMHMM_hmm_logF`, logf1, logf2, pi, gamma)
}

hmm_logB <- function(logf1, logf2, pi, gamma) {
    .Call(`_ZIMHMM_hmm_logB`, logf1, logf2, pi, gamma)
}

hmm_P1 <- function(logF, logB) {
    .Call(`_ZIMHMM_hmm_P1`, logF, logB)
}

hmm_P2 <- function(logF, logB, logf1, logf2, gamma) {
    .Call(`_ZIMHMM_hmm_P2`, logF, logB, logf1, logf2, gamma)
}

my_dnbinom <- function(x, mu, size, lg) {
    .Call(`_ZIMHMM_my_dnbinom`, x, mu, size, lg)
}

MHMMmean <- function(XMAT, BETA, RANDOM, OFFSETVEC, N, M, K) {
    .Call(`_ZIMHMM_MHMMmean`, XMAT, BETA, RANDOM, OFFSETVEC, N, M, K)
}

MHMMLik <- function(YVEC, ZEROINFL, MU, DISP, N, M, K) {
    .Call(`_ZIMHMM_MHMMLik`, YVEC, ZEROINFL, MU, DISP, N, M, K)
}

integrand <- function(U, YVEC, XMAT, BETA, DISP, P, GAMMA, OFFSETVEC, ZEROINFL, W, SIGMA2) {
    .Call(`_ZIMHMM_integrand`, U, YVEC, XMAT, BETA, DISP, P, GAMMA, OFFSETVEC, ZEROINFL, W, SIGMA2)
}

generateHMM <- function(GAMMA, m) {
    .Call(`_ZIMHMM_generateHMM`, GAMMA, m)
}

